### ISSUE TITLE
Audio Sample files

### ISSUE THREAD

**Issue by sz-dev** [hyvart/Unjammit#39]
Hi,

This is the first time I am running the project, may be following question is very basic.

I executed the windows client, I did not get the following UI. 
How can i get sample audio files in order to experience following 
![image](https://user-images.githubusercontent.com/66676736/103958023-7ae05100-5165-11eb-8ece-23808e009705.png)

**Comment by JunielKatarn** [comment]
Hi, @sz-dev. That UI is the legacy client from which Unjammit is forked: https://github.com/maxton/Jam.NET.
It is more feature complete, but not under development.
To run it, you can select `Jam.NET` as the main project in Visual Studio, or just install it at http://unjammit.com/clickonce/Jam.NET.application.

**Comment by JunielKatarn** [comment]
Closing, as the question has been answered.
